package com.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.entity.BagInfo;
import com.entity.PileInfo;
import com.entity.ScreenInfo;
import com.entity.TrayInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig screenInfoDaoConfig;
    private final DaoConfig trayInfoDaoConfig;
    private final DaoConfig pileInfoDaoConfig;
    private final DaoConfig bagInfoDaoConfig;

    private final ScreenInfoDao screenInfoDao;
    private final TrayInfoDao trayInfoDao;
    private final PileInfoDao pileInfoDao;
    private final BagInfoDao bagInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        screenInfoDaoConfig = daoConfigMap.get(ScreenInfoDao.class).clone();
        screenInfoDaoConfig.initIdentityScope(type);

        trayInfoDaoConfig = daoConfigMap.get(TrayInfoDao.class).clone();
        trayInfoDaoConfig.initIdentityScope(type);

        pileInfoDaoConfig = daoConfigMap.get(PileInfoDao.class).clone();
        pileInfoDaoConfig.initIdentityScope(type);

        bagInfoDaoConfig = daoConfigMap.get(BagInfoDao.class).clone();
        bagInfoDaoConfig.initIdentityScope(type);

        screenInfoDao = new ScreenInfoDao(screenInfoDaoConfig, this);
        trayInfoDao = new TrayInfoDao(trayInfoDaoConfig, this);
        pileInfoDao = new PileInfoDao(pileInfoDaoConfig, this);
        bagInfoDao = new BagInfoDao(bagInfoDaoConfig, this);

        registerDao(ScreenInfo.class, screenInfoDao);
        registerDao(TrayInfo.class, trayInfoDao);
        registerDao(PileInfo.class, pileInfoDao);
        registerDao(BagInfo.class, bagInfoDao);
    }
    
    public void clear() {
        screenInfoDaoConfig.clearIdentityScope();
        trayInfoDaoConfig.clearIdentityScope();
        pileInfoDaoConfig.clearIdentityScope();
        bagInfoDaoConfig.clearIdentityScope();
    }

    public ScreenInfoDao getScreenInfoDao() {
        return screenInfoDao;
    }

    public TrayInfoDao getTrayInfoDao() {
        return trayInfoDao;
    }

    public PileInfoDao getPileInfoDao() {
        return pileInfoDao;
    }

    public BagInfoDao getBagInfoDao() {
        return bagInfoDao;
    }

}
