package com.fanfull.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table FINGER.
 */
public class Finger {

    private Long id;
    private int finger_id;
    /** Not-null value. */
    private String user_id;
    private int finger_version;
    private int finger_sno;

    public Finger() {
    }

    public Finger(Long id) {
        this.id = id;
    }

    public Finger(Long id, int finger_id, String user_id, int finger_version, int finger_sno) {
        this.id = id;
        this.finger_id = finger_id;
        this.user_id = user_id;
        this.finger_version = finger_version;
        this.finger_sno = finger_sno;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getFinger_id() {
        return finger_id;
    }

    public void setFinger_id(int finger_id) {
        this.finger_id = finger_id;
    }

    /** Not-null value. */
    public String getUser_id() {
        return user_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public int getFinger_version() {
        return finger_version;
    }

    public void setFinger_version(int finger_version) {
        this.finger_version = finger_version;
    }

    public int getFinger_sno() {
        return finger_sno;
    }

    public void setFinger_sno(int finger_sno) {
        this.finger_sno = finger_sno;
    }

}
